# Generated by Django 2.2.6 on 2019-11-14 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post fields_startups_and_tags_optional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'pub_date', 'ordering': ['-pub_date', 'title'], 'permissions': (('view_future_post', 'Can view unpublished Post'),), 'verbose_name': 'blog post'},
        ),
    ]
