# Generated by Django 2.2.6 on 2019-11-07 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0005_newslink_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='newslink',
            unique_together={('slug', 'startup')},
        ),
    ]
